### ISSUE TITLE
bug: miss env selector when run github action

### ISSUE THREAD

**Issue by qweasd1** [stateful/runme#557]
Hi, 
first, runme is a really nice young tool. Just want to report a bug when I run it inside vscode for github action. 
for one of my github action, I have one input as "environment" type. 
```yaml
workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run Deployment'
        type: environment
        required: true
        default: stage
      synthetic_test_status:
        description: 'Status of Datadog Synthetic test'
        type: choice
        default: live
        options:
          - live
          - paused
 ...
```

however, it can't shown in vs code plugin 
<img width="708" alt="image" src="https://github.com/stateful/runme/assets/10579528/7f22d89f-4974-481e-8729-adabb8d9e87e">

So seems this is bug in vs code plugin.
